### ISSUE TITLE
Does transcoding always cause a delay?

### ISSUE THREAD

**Issue by joepadmiraal** [UbiCastTeam/qr-lipsync#2]
Hi,

I have a question about transcoding the source qr code files.
When I convert the file with FFmpeg it always seem to introduce lipsync issues.
For example I tried to move the default 30fps file into an mp4 container.
In order to minimize the possibility of introducing AV sync issues I'm not encoding the video again (`-vcodec copy`) and I'm keeping the timestamps (`-vsync 0`).
However when I run qr-lipsync-detect it gives me a median delay of 66ms while the original gives me median of 0.
I also tried it with the FFmpeg defaults (so it will encode the video again) and that also gives 66ms delay.

Is it not possible to transcode without introducing serious delays (2 frames in my case)?

I attached both video's in [videos.zip](https://github.com/UbiCastTeam/qr-lipsync/files/5022790/videos.zip).
Here you can see my ffmpeg command and the qr-lipsync-detect command:

```
ffmpeg -vsync 0 -i cam1-qrcode-blue-30.qt -vcodec copy qr.mp4
ffmpeg version N-94710-g5f993d2d1d Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 10 (GCC)
  configuration: --enable-gpl --enable-nonfree --enable-openssl --enable-version3 --disable-sdl2 --enable-debug --disable-ffplay --disable-libxcb --disable-libxcb-shm --disable-indev=sndio --disable-outdev=sndio --disable-outdev=xv --enable-libfreetype --enable-fontconfig --enable-libpulse --enable-libvmaf --enable-libx264 --enable-libsrt --pkg-config-flags=--static --prefix=output
Livery build 1
  libavutil      56. 33.100 / 56. 33.100
  libavcodec     58. 55.100 / 58. 55.100
  libavformat    58. 30.100 / 58. 30.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 58.100 /  7. 58.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'cam1-qrcode-blue-30.qt':
  Metadata:
    major_brand     : qt  
    minor_version   : 537199360
    compatible_brands: qt  
    creation_time   : 2020-08-04T08:12:04.000000Z
    encoder         : x264
  Duration: 00:00:30.00, start: 0.000000, bitrate: 1288 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt470bg/smpte170m/bt709, progressive), 640x360 [SAR 1:1 DAR 16:9], 518 kb/s, 30 fps, 30 tbr, 3k tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2020-08-04T08:12:04.000000Z
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: pcm_s16le (sowt / 0x74776F73), 48000 Hz, mono, s16, 768 kb/s (default)
    Metadata:
      creation_time   : 2020-08-04T08:12:04.000000Z
      handler_name    : SoundHandler
File 'qr.mp4' already exists. Overwrite ? [y/N] y
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
Output #0, mp4, to 'qr.mp4':
  Metadata:
    major_brand     : qt  
    minor_version   : 537199360
    compatible_brands: qt  
    encoder         : Lavf58.30.100
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt470bg/smpte170m/bt709, progressive), 640x360 [SAR 1:1 DAR 16:9], q=2-31, 518 kb/s, 30 fps, 30 tbr, 12k tbn, 3k tbc (default)
    Metadata:
      creation_time   : 2020-08-04T08:12:04.000000Z
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 69 kb/s (default)
    Metadata:
      creation_time   : 2020-08-04T08:12:04.000000Z
      handler_name    : SoundHandler
      encoder         : Lavc58.55.100 aac
frame=  900 fps=0.0 q=-1.0 Lsize=    1970kB time=00:00:30.01 bitrate= 537.6kbits/s speed= 262x    
video:1899kB audio:44kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.371089%
[aac @ 0x28a3840] Qavg: 62796.785



[joep@laptopjoep-localdomain:~/Documents/lls/AVSync/comparison]
% qr-lipsync-detect.py qr.mp4                                  
2020-08-04 16:43:26,472 detector     INFO     starting pipeline
progressreport0 (00:00:01): 4 / 30 seconds (13.3 %)
progressreport0 (00:00:02): 13 / 30 seconds (43.3 %)
progressreport0 (00:00:03): 23 / 30 seconds (76.7 %)
progressreport0 (00:00:03): 29 / 30 seconds (96.7 %)
2020-08-04 16:43:29,650 detector     INFO     found 900 qrcodes (30 containing beep information) and 30 beeps in audio
2020-08-04 16:43:29,650 detector     INFO     Processing took 3.18s (283 fps)
2020-08-04 16:43:29,650 detector     INFO     Wrote file qr_data.txt
2020-08-04 16:43:29,775 qr-lipsync-analyze INFO     Reading file qr_data.txt
2020-08-04 16:43:29,784 qr-lipsync-analyze INFO     Finished reading, took 0s
2020-08-04 16:43:29,784 qr-lipsync-analyze INFO     Checking AV sync
2020-08-04 16:43:29,784 qr-lipsync-analyze INFO     Checking video stats
2020-08-04 16:43:29,784 qr-lipsync-analyze INFO     Detected frame duration of 33.3ms
2020-08-04 16:43:29,785 qr-lipsync-analyze INFO     ---------------------------- Global report --------------------------
2020-08-04 16:43:29,785 qr-lipsync-analyze INFO     Total duplicated frames : 0/900 (0.0%)
2020-08-04 16:43:29,785 qr-lipsync-analyze INFO     Total dropped frames : 0/900 (0.0%)
2020-08-04 16:43:29,785 qr-lipsync-analyze INFO     Average framerate (based on qrcode content) is 30
2020-08-04 16:43:29,785 qr-lipsync-analyze INFO     Median delay between beep and qrcode : 66 ms (2 frames), video is late; average: -64.9ms (-1.0 frames), max: -67ms at 0:0:4.933
2020-08-04 16:43:29,785 qr-lipsync-analyze INFO     Warning, -1 ms/s drift detected
2020-08-04 16:43:29,785 qr-lipsync-analyze INFO     Video duration is 30.0s (0:0:30.000)
2020-08-04 16:43:29,785 qr-lipsync-analyze INFO     Audio duration is 30.016s (0:0:30.016)
2020-08-04 16:43:29,785 qr-lipsync-analyze INFO     Missed 0 beeps out of 30 qrcodes (0%)
2020-08-04 16:43:29,785 qr-lipsync-analyze INFO     ---------------------------------------------------------------------
2020-08-04 16:43:29,785 qr-lipsync-analyze INFO     Wrote results as JSON into qr_data.report.json
2020-08-04 16:43:29,785 qr-lipsync-analyze ERROR    Statistic median_av_delay_frames is not 0 (-2), exiting with error

```

**Comment by fthiery** [comment]
Hi, sorry for the delay (holidays !).

In your case, you are re-encoding audio to AAC; aac is known to add 20-40ms of delay (https://github.com/UbiCastTeam/qr-lipsync/blob/master/qrlipsync/detect.py#L57 ). I'm unsure on the effects of `-vsync 0`.

To respond to your initial question, if the transcoding is done properly, it should not induce a latency. Also, make sure to run this with a recent-enough gstreamer (see https://github.com/UbiCastTeam/qr-lipsync/commit/11b36c5977ad435c0bee42cc5c45825151e141b9)

**Comment by fthiery** [comment]
Btw, you can generate mp4/AAC samples directly with `-f mp4`

**Comment by fthiery** [comment]
> I'm curious though, isn't the playback position based on the PTS values?
> Those PTS values are not influenced by priming right?

I don't think so, because the priming samples is supposed to be stored specifically in the container (e.g. edit list info in mp4s) see https://github.com/mstorsjo/fdk-aac/issues/24#issuecomment-68954054

> I'm testing a program I created which get's raw video from a capture card and encodes it to an mp4 file.
> So I was hoping to use qrlipsync to verify how good the capture card and my program is performing.

That's what we wrote this for too (and it does the job for us). Is your recording program using ffmpeg with `-vcodec copy -vsync 0` ? In any case, your recording app may not start all buffers at 0, which could explain the latency.

**Comment by joepadmiraal** [comment]
I used ` -vcodec copy -vsync 0` for this conversion so FFmpeg would not interfere with the timestamps.
In my recording program I was using vsync but I'm now rewriting the whole thing to get timestamps from the capture card sdk directly. 

This is the graph output from an mp4 conversion:
```
-0.029	-29
0.955	-45
1.96	-40
2.956	-44
3.955	-45
4.957	-43
5.959	-41
6.955	-45
7.957	-43
8.956	-44
9.961	-39
10.957	-43
11.956	-44
12.955	-45
13.957	-43
14.956	-44
15.955	-45
16.957	-43
17.956	-44
18.955	-45
19.957	-43
20.956	-44
21.955	-45
22.957	-43
23.956	-44
24.955	-45
25.957	-43
26.956	-44
27.955	-45
28.957	-43
```
There is quite some difference between the smallest and the largest value.
Even if I don't count the first value the lowest is -39 and the highest is -45 which is a difference of 6 ms.
If it's only a priming issue I would expect a constant delay instead of 6 ms fluctuation.
Of is 6 ms expected?

**Comment by joepadmiraal** [comment]
Yes, but these numbers are from the FFmpeg transcode of the original .qt file.
It's from the attached videos.zip file.
So there is no capture card involved, it's just converting to mp4(h264/aac).

Is 6ms still normal in that case?

**Comment by fthiery** [comment]
I tried too, and i reproduce the problem. The only conclusion seems to be that ffmpeg somehow adds some kind of latency when reencoding audio. Running `-vcodec copy -acodec copy` works fine though.

Even with the reference video you see some fluctuations:
```
time	delay
0.003	3
0.999	-1
2.004	4
3.0	0
3.999	-1
5.001	1
6.0	0
6.999	-1
8.001	1
9.0	0
10.005	5
11.001	1
12.0	0
12.999	-1
14.001	1
15.0	0
15.999	-1
17.001	1
18.0	0
18.999	-1
20.001	1
21.0	0
21.999	-1
23.007	7
24.0	0
24.999	-1
26.001	1
27.0	0
27.999	-1
29.001	1
```

I think it may be related to how the audio beeps are detected: we use fourier transform (spectrum) to detect the dominant frequencies, but because the frequency of the audiotestsrc changes i suspect that it induces these offsets. So i would say that a fluctuation of 6ms seems perfectly fine.

However, you do have a 44ms median offset that is added by ffmpeg.

**Comment by joepadmiraal** [comment]
Are those numbers (-1 to 7) from your test coming from qr.mp4 in my videos.zip file?

That would be very interesting because that would probably mean something is wrong with my installation.

**Comment by fthiery** [comment]
No, these numbers is the graph from analyzing the reference sample (so that's the supposedly "perfect" data).

**Comment by joepadmiraal** [comment]
Alright thanks for the insights.
Let's close this ticket as there is not much we can do about it.
