### ISSUE TITLE
Video sample for 50i

### ISSUE THREAD

**Issue by Ady-C** [UbiCastTeam/qr-lipsync#5]
Hello, 

I can't seem to get the qr-lipsync-generate.py working. Can I have a video sample like cam1-qrcode-blue-30.qt for 50i ? And maybe -f mp4 ?
If I use the one for 30fps I get readings like: Median delay between beep and qrcode : 5 ms (0 frames), video is late; average: 40ms (1.0 frames), max: 285ms at 0:0:0.365
Thank you,

**Comment by fthiery** [comment]
Hi

Did you try the following:

```
make build
make generate
```

It should produce the `cam1-qrcode-blue-30.qt` file in the working directory.

You can pass options using
```
$ make generate ARGS='-h'
docker run -v /home/fthiery/src/ubicast/devtools/qr-lipsync:/opt/src registry.ubicast.net/devtools/qr-lipsync:main qr-lipsync-generate.py --output-dir /opt/src -h
usage: qr-lipsync-generate.py [-h] [-v] [-a] [-t] [-o OUTPUT_DIR]
                              [-q QRCODE_NAME] [-d DURATION] [-r FRAMERATE]
                              [-s SIZE] [-f {mp4,qt,webm+vp8,webm+vp9}]
                              [-b {snow,black,white,red,green,blue,smpte,pinwheel}]

Generate videos suitable for measuring lipsync with qrcodes

options:
  -h, --help            show this help message and exit
  -v, --verbosity       increase output verbosity (default: False)
  -a, --disable-audio   enable audio track (default: False)
  -t, --enable-textoverlay
                        enable text overlay (shows timecode) (default: True)
  -o OUTPUT_DIR, --output-dir OUTPUT_DIR
                        output directory (default: .)
  -q QRCODE_NAME, --qrcode-name QRCODE_NAME
                        name inserted into the qrcode pattern (default: cam1)
  -d DURATION, --duration DURATION
                        duration in seconds (default: 30)
  -r FRAMERATE, --framerate FRAMERATE
                        framerate (default: 30)
  -s SIZE, --size SIZE  video size (default: 640x360)
  -f {mp4,qt,webm+vp8,webm+vp9}, --format {mp4,qt,webm+vp8,webm+vp9}
                        video format: qt/h264/pcm (default), mp4/h264/aac or
                        webm/vp8/vorbis (default: qt)
  -b {snow,black,white,red,green,blue,smpte,pinwheel}, --background {snow,black,white,red,green,blue,smpte,pinwheel}
                        background color (default: blue)
```

As for i support, it's not in scope yet but contributions are welcome.

**Comment by Ady-C** [comment]
I get this when I try to generate : qrcode_generator ERROR    Failed to start pipeline (gst_parse_error: no property "sine-periods-per-tick" in element "audio_src" (2)), exiting with error

**Comment by fthiery** [comment]
Please include the list of actions you do to launch the processing. Are you using docker as advised above and in the readme ? Your message seems to indicate you have an old gstreamer version that lacks a property on the audiotestsrc element.

**Comment by Ady-C** [comment]
I don't use Docker. Just Ubuntu in wsl Windows. Can I somehow upgrade the gstreamer ?

**Comment by fthiery** [comment]
Sure you can, but i wouldn't know how, sorry. I suggest that if you're not confident in doing so by yourself, you should try with docker (which manages everything for you). Maybe you can try with the most recent Ubuntu WSL release, that could work. I think you'll want Gstreamer 1.20 at least.

**Comment by Ady-C** [comment]
I will try installing and using Docker. Thank you for your quick reply.
